export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const ORDER_BUTTON_TOGGLE = "ORDER_BUTTON_TOGGLE";
export const RESET_STORE ="RESET_STORE";


export const ORDERS_LOADED ="ORDERS_LOADED";
export const ORDERS_LOADING_FAILED = "ORDERS_LOADING_FAILED";

export const AUTH_SUCCESS ="AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
